var a=2, b=10, c=16;
var r=Math.pow(a,b);
console.log(r);
var r=Math.round(a);
console.log(r);
var r=Math.ceil(a);
console.log(r);
var r=Math.floor(a);
console.log(r);
var r=Math.abs(-a);
console.log(r);
var r=Math.max(a,b,c);
console.log(r);
var r=Math.min(a,b,c);
console.log(r);
var r=Math.random();
console.log(r);
var r=Math.PI;
console.log(r);
var r=Math.E;
console.log(r);
var r=Math.sqrt(a);
console.log(r);
var r=Math.pow(c,(1/2)); //quando b<1 vc acha a raiz// 
console.log(r);
var r=Math.sin(30);
console.log(r);
var r=Math.log(a);
console.log(r);
var r=Math.log(100)/Math.LN10;
console.log(r);
var r=Math.log(512)/Math.LN2;
console.log(r);
var r=Math.exp(1);
console.log(r);
